#!/usr/bin/env npx tsx
/**
 * build-autogen-blog.ts — Compile 10 MD files from blog-autogen-2026-04-12/
 * into a single TypeScript export `BLOG_ARTICLES_AUTOGEN_2026_04_12`
 * matching the BlogArticle interface.
 *
 * Generated file: src/data/blog-autogen-2026-04-12.ts
 * Imported by: src/data/blog.ts which spreads it into BLOG_ARTICLES.
 */

import { readdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";

const DIR = join(process.cwd(), "src", "data", "blog-autogen-2026-04-12");
const OUT = join(process.cwd(), "src", "data", "blog-autogen-2026-04-12.ts");

interface ParsedArticle {
  slug: string;
  title: string;
  description: string;
  keywords: string[];
  category: string;
  published: string;
  content: string;
}

function parseFrontmatter(raw: string): ParsedArticle {
  const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
  if (!match) throw new Error("No frontmatter");
  const fm = match[1];
  const content = match[2].trim();

  // Tolerant YAML-ish parser for our simple frontmatter
  const get = (key: string) => {
    const re = new RegExp(`^${key}:\\s*(.+)$`, "m");
    const m = fm.match(re);
    return m ? m[1].trim() : "";
  };

  const stripQuotes = (s: string) =>
    s.replace(/^["']/, "").replace(/["']$/, "").trim();

  const slug = stripQuotes(get("slug"));
  const title = stripQuotes(get("title"));
  const description = stripQuotes(get("description"));
  const category = stripQuotes(get("category"));
  const published = stripQuotes(get("published"));

  // Keywords: either inline array [a, b] or multi-line list
  let keywords: string[] = [];
  const kwLine = get("keywords");
  if (kwLine.startsWith("[")) {
    try {
      keywords = JSON.parse(kwLine.replace(/'/g, '"'));
    } catch {
      keywords = kwLine
        .replace(/^\[|\]$/g, "")
        .split(",")
        .map((s) => stripQuotes(s));
    }
  }

  return { slug, title, description, keywords, category, published, content };
}

function computeReadingTime(content: string): number {
  const words = content.split(/\s+/).filter(Boolean).length;
  return Math.max(1, Math.round(words / 200));
}

function generateExcerpt(content: string, max = 220): string {
  // Strip HTML comments, frontmatter artifacts, skip H1, take first paragraph
  const body = content
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/^#\s.*$/m, "")
    .trim();
  const para = body.split(/\n\n/).find((p) => p.trim().length > 50) ?? "";
  const plain = para
    .replace(/\*\*(.+?)\*\*/g, "$1")
    .replace(/\*(.+?)\*/g, "$1")
    .replace(/`(.+?)`/g, "$1")
    .replace(/\[(.+?)\]\([^)]+\)/g, "$1")
    .replace(/\s+/g, " ")
    .trim();
  if (plain.length <= max) return plain;
  return plain.slice(0, max - 1).trimEnd() + "…";
}

function main() {
  const files = readdirSync(DIR).filter((f) => f.endsWith(".md"));
  console.log(`Reading ${files.length} articles from ${DIR}`);

  const articles = files.map((f) => {
    const raw = readFileSync(join(DIR, f), "utf-8");
    const parsed = parseFrontmatter(raw);
    const readingTime = computeReadingTime(parsed.content);
    const excerpt = generateExcerpt(parsed.content);
    return {
      slug: parsed.slug,
      title: parsed.title,
      excerpt,
      content: parsed.content,
      tags: parsed.keywords,
      publishedAt: parsed.published,
      readingTime,
      glossaryLinks: [] as string[],
      seoTitle: parsed.title,
      seoDescription: parsed.description,
    };
  });

  const tsOutput = `// AUTO-GENERATED by scripts/build-autogen-blog.ts — do not edit.
// Source: src/data/blog-autogen-2026-04-12/*.md (10 SEO articles 2026-04-12).
// Regenerate: npx tsx scripts/build-autogen-blog.ts

import type { BlogArticle } from "./blog-types";

export const BLOG_ARTICLES_AUTOGEN_2026_04_12: BlogArticle[] = ${JSON.stringify(
    articles,
    null,
    2,
  )};
`;

  writeFileSync(OUT, tsOutput, "utf-8");
  console.log(`Wrote ${articles.length} articles to ${OUT}`);
  console.log("Slugs:");
  articles.forEach((a) =>
    console.log(`  - /blog/${a.slug} (${a.readingTime} min)`),
  );
}

main();
