-- entity_seo: per-tag/character/series SEO content
-- Generated by enrich-entity-seo.mjs (run via SEO autopilot cron).

CREATE TABLE IF NOT EXISTS entity_seo (
  entity_type  TEXT NOT NULL,                    -- 'tag' | 'character' | 'series'
  slug         TEXT NOT NULL,                    -- canonical slug (matches URL)
  display_name TEXT NOT NULL,
  video_count  INTEGER NOT NULL DEFAULT 0,
  intro        TEXT NOT NULL DEFAULT '',         -- 200-400 word SEO body
  faq          JSONB NOT NULL DEFAULT '[]',      -- [{q, a}, ...]
  meta         JSONB NOT NULL DEFAULT '{}',      -- top related entities, etc.
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (entity_type, slug)
);

CREATE INDEX IF NOT EXISTS entity_seo_type_idx ON entity_seo (entity_type);
CREATE INDEX IF NOT EXISTS entity_seo_age_idx ON entity_seo (generated_at);
