/**
 * blog-internal-links.ts — Dynamic internal links to append to blog articles
 *
 * Generated by seo-autopilot.mjs updateInternalLinks(). Maps article slugs
 * to arrays of internal links that should be appended at render time.
 * This avoids modifying the actual article content in blog.ts.
 *
 * The blog/[slug]/page.tsx renders these as a "Related Content on iku.gg"
 * section at the bottom of each article.
 */

export interface InternalLink {
  text: string;
  href: string;
}

export interface ArticleLinks {
  articleSlug: string;
  linksToAdd: InternalLink[];
  updatedAt: string;
}

export const BLOG_INTERNAL_LINKS: ArticleLinks[] = [];

/**
 * Get internal links for a specific article slug.
 * Returns undefined if no links have been generated for this article.
 */
export function getInternalLinksForArticle(slug: string): ArticleLinks | undefined {
  return BLOG_INTERNAL_LINKS.find((a) => a.articleSlug === slug);
}
