/**
 * characters-seo.ts — SEO-enriched descriptions and FAQs for top 30 characters
 *
 * Generated by seo-autopilot.mjs enrichCharacterPages(). Each entry contains:
 * - 200-word SEO description mentioning character, series, tags, popularity
 * - 3 FAQ items for FAQPage schema.org markup
 *
 * This file is NOT imported by characters.ts — it's a standalone data source
 * that character pages can optionally merge at render time.
 */

export interface CharacterSEO {
  slug: string;
  name: string;
  series: string;
  searchVolume: number;
  seoDescription: string;
  faq: Array<{ question: string; answer: string }>;
  generatedAt: string;
}

export const CHARACTERS_SEO: CharacterSEO[] = [];

/**
 * Lookup a character's SEO data by slug.
 * Returns undefined if the character hasn't been enriched yet.
 */
export function getCharacterSEO(slug: string): CharacterSEO | undefined {
  return CHARACTERS_SEO.find((c) => c.slug === slug);
}
